'use strict';
if (new URLSearchParams(location.search).get('demo') === '1') {
'use strict';
const STORAGE = 'matchcats-panels-v1';
const navigation = [ ['dashboard','◫','Start'],['cats','♧','Moje koty'],['search','⌕','Szukaj kota'],['messages','✉','Rozmowy'],['documents','▤','Dokumenty'],['settings','⚙','Ustawienia'] ];
const initialCats = [
 {id:1,name:'Luna',breed:'Maine Coon',sex:'FEMALE',birth:'2022-05-18',city:'Warszawa',owner:'Wiktoria',own:true,available:true,tone:0,documents:['Rodowód','Wynik badania genetycznego'],award:'Wystawa — wpis przykładowy',description:'Spokojna, ciekawska kotka z hodowli demonstracyjnej. Szczegóły badań, pochodzenia i warunki krycia należy omówić z właścicielem.'},
 {id:2,name:'Oliver',breed:'Maine Coon',sex:'MALE',birth:'2021-09-12',city:'Kraków',owner:'Anna · Leśna Przystań',own:false,available:true,tone:1,documents:['Rodowód','Wynik badania genetycznego'],award:'Wystawa — wpis przykładowy',description:'Przykładowy profil kocura. Właściciel udostępnia informacje o pochodzeniu i badaniach podczas rozmowy. To profil demonstracyjny, a nie oferta rzeczywistej hodowli.'},
 {id:3,name:'Bella',breed:'Ragdoll',sex:'FEMALE',birth:'2023-02-04',city:'Gdańsk',owner:'Marta · Błękitny Dom',own:false,available:true,tone:2,documents:['Rodowód'],award:'',description:'Łagodna kotka w przykładowej hodowli. Dokumenty wymagają indywidualnego sprawdzenia przed podjęciem decyzji.'},
 {id:4,name:'Leo',breed:'Brytyjski krótkowłosy',sex:'MALE',birth:'2022-10-10',city:'Poznań',owner:'Piotr · Srebrny Ogród',own:false,available:true,tone:3,documents:['Rodowód'],award:'Wystawa — wpis przykładowy',description:'Przykładowy profil kota brytyjskiego. Porozmawiaj z hodowcą, aby poznać warunki i historię badań.'},
 {id:5,name:'Milo',breed:'Ragdoll',sex:'MALE',birth:'2023-03-20',city:'Wrocław',owner:'Wiktoria',own:true,available:false,tone:2,documents:[],award:'',description:'Profil demonstracyjny. Kot obecnie nie jest dostępny do rozmów o kryciu.'}
];
const initialChats = [{id:1,catId:2,owner:'Anna · Leśna Przystań',messages:[{mine:false,text:'Dzień dobry! Chętnie porozmawiam o Oliverze i udostępnię informacje o jego badaniach.',time:'10:24'}]},{id:2,catId:3,owner:'Marta · Błękitny Dom',messages:[{mine:false,text:'Dzień dobry, jakie informacje o hodowli chciałaby Pani poznać?',time:'Wczoraj'}]}];
let state = {cats:structuredClone(initialCats),chats:structuredClone(initialChats),profile:{name:'Wiktoria',kennel:'Twoja hodowla',city:'Warszawa'}};
let storageAvailable = true;
try {const saved=JSON.parse(localStorage.getItem(STORAGE));if(saved&&Array.isArray(saved.cats)&&Array.isArray(saved.chats)&&saved.profile&&saved.cats.every(c=>Number.isSafeInteger(c.id)&&Array.isArray(c.documents))&&saved.chats.every(c=>Number.isSafeInteger(c.id)&&Array.isArray(c.messages)))state=saved;}catch{storageAvailable=false;}
state.language=state.language==='en'?'en':'pl';
let activeChat=state.chats[0]?.id;
let pendingSearch = null;
let toastTimer;
const main=document.querySelector('#main');
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sexLabel=c=>c.sex==='MALE'?'Kocur ♂':'Kotka ♀';
const age=c=>{const birth=new Date(c.birth);if(Number.isNaN(birth.getTime()))return 'Wiek niepodany';const now=new Date();let years=now.getFullYear()-birth.getFullYear();if(now.getMonth()<birth.getMonth()||(now.getMonth()===birth.getMonth()&&now.getDate()<birth.getDate()))years--;return years<=0?'Poniżej roku':`${years} ${years===1?'rok':years<5?'lata':'lat'}`;};
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state));storageAvailable=true;return true;}catch{storageAvailable=false;toast('Nie udało się zapisać danych na urządzeniu. Zmiany działają do zamknięcia strony.');return false;}}
function toast(message){const box=document.querySelector('#toast');box.textContent=matchCatsTranslate(message,state.language);box.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.style.display='none',4500);}
function catVisual(cat) {
 const breeds = {'Maine Coon':'maine','Ragdoll':'ragdoll','Brytyjski krótkowłosy':'british'};
 const portrait = cat.id <= 5 ? breeds[cat.breed] : null;
 if (!portrait) return '<div class="cat-placeholder" role="img" aria-label="Nie dodano zdjęcia kota">'+uiIcon('cats')+'</div>';
 return '<div class="cat-portrait '+portrait+'" role="img" aria-label="Wygenerowane zdjęcie kota; profil demonstracyjny"></div>';
}
function uiIcon(name){const shapes={dashboard:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/>',cats:'<ellipse cx="12" cy="16" rx="6" ry="4"/><ellipse cx="5" cy="9" rx="2" ry="3"/><ellipse cx="10" cy="6" rx="2" ry="3"/><ellipse cx="16" cy="6" rx="2" ry="3"/><ellipse cx="20" cy="10" rx="2" ry="3"/>',search:'<circle cx="10.5" cy="10.5" r="7"/><path d="m16 16 5 5"/>',messages:'<path d="M21 11a8 8 0 0 1-8 8H8l-5 3V11a8 8 0 0 1 8-8h2a8 8 0 0 1 8 8Z"/><path d="M7 10h10M7 14h6"/>',documents:'<path d="M5 3h10l4 4v14H5Z M15 3v5h4M8 12h8M8 16h8"/>',settings:'<circle cx="12" cy="12" r="4"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(shapes[name]||shapes.cats)+'</svg>';}
function heading(title,subtitle,action=''){return `<div class="heading"><div><span class="eyebrow">PRZESTRZEŃ DLA DOBREJ HODOWLI</span><h1>${title}</h1><p class="muted">${subtitle}</p></div>${action}</div>`;}
function catCard(c){return `<article class="cat-card"><div class="cat-picture">${catVisual(c)}<span class="picture-badge">${c.available?'Dostępność zgłoszona':'Profil hodowlany'}</span></div><div class="cat-body"><div class="cat-title"><h3>${escapeHTML(c.name)}</h3><span class="sex-label">${sexLabel(c)}</span></div><p class="cat-meta">${escapeHTML(c.breed)} · ${age(c)}</p><div class="tag-row"><span class="tag">${c.documents.length?'Dokumenty: wpis przykładowy':'Dokumenty niepodane'}</span>${c.award?'<span class="tag gold">✧ Wystawy</span>':''}</div><div class="cat-bottom"><span class="city">⌖ ${escapeHTML(c.city)}</span><button class="button subtle" data-cat="${c.id}">Zobacz profil →</button></div></div></article>`;}
function chatRow(c,selected=false){const latest=c.messages.at(-1);return `<button class="conversation-row ${selected?'selected':''}" data-chat="${c.id}"><span class="initials">${escapeHTML(c.owner.slice(0,1))}</span><span><strong>${escapeHTML(c.owner)}</strong><small>${escapeHTML(latest?.text||'Rozpocznij rozmowę')}</small></span>${selected?'':`<time>${escapeHTML(latest?.time||'')}</time>`}</button>`;}
function dashboard(){
 const own=state.cats.filter(c=>c.own);
 const suggestions=state.cats.filter(c=>!c.own&&c.available);
 return heading(`Dzień dobry, ${escapeHTML(state.profile.name)}`,'Twoja hodowla w jednym miejscu.')+
 `<section class="hero"><div class="hero-copy"><span class="eyebrow">POZNAJ KOTY I ICH HODOWCÓW</span><h2>Poznaj koty.<br>Poznaj ich hodowców.</h2><p>Odkrywaj profile, poznawaj hodowców i dbaj o swoją hodowlę.</p><div class="hero-actions"><a href="#search" class="button primary">${uiIcon('search')} Szukaj partnera</a><button class="button secondary" data-add>＋ Dodaj swojego kota</button></div><ol class="journey" aria-label="Jak zacząć"><li><span>1</span>Wyszukaj kota</li><li><span>2</span>Sprawdź profil</li><li><span>3</span>Napisz do hodowcy</li></ol></div><div class="hero-art"><img src="assets/sky-hero.jpg" alt="" fetchpriority="high" width="1536" height="1024"><div class="hero-tag"><strong>Najpierw poznaj kota</strong>Rodowód · Badania · Osiągnięcia</div></div></section>
 <form class="dashboard-search" id="dashboard-search" aria-label="Szybkie wyszukiwanie kotów"><label>Rasa<select name="breed"><option value="">Wszystkie rasy</option><option>Maine Coon</option><option>Ragdoll</option><option>Brytyjski krótkowłosy</option><option>Syberyjski</option></select></label><label>Płeć<select name="sex"><option value="">Dowolna</option><option value="MALE">Kocur</option><option value="FEMALE">Kotka</option></select></label><label>Miasto<input name="city" type="search" placeholder="Wszystkie miasta"></label><button class="button primary" type="submit">${uiIcon('search')} Szukaj</button></form>

 <section><div class="section-heading"><div><h2>Odkryj profile kotów</h2><p class="muted">Otwórz profil, aby poznać kota i jego właściciela.</p></div><a class="button secondary" href="#search">Wszystkie koty →</a></div><div class="cat-grid">${suggestions.slice(0,3).map(catCard).join('')}</div></section>
 <section class="quick-actions" aria-label="Najważniejsze czynności"><a class="quick-action" href="#cats"><span class="quick-icon">${uiIcon('cats')}</span><span><strong>Moje koty</strong><small>Profile w Twojej hodowli: ${own.length}</small></span><span class="action-arrow">→</span></a><a class="quick-action" href="#search"><span class="quick-icon">${uiIcon('search')}</span><span><strong>Szukaj partnera</strong><small>Przeglądaj koty innych hodowców</small></span><span class="action-arrow">→</span></a><a class="quick-action" href="#messages"><span class="quick-icon">${uiIcon('messages')}</span><span><strong>Rozmowy</strong><small>Otwórz swoje rozmowy: ${state.chats.length}</small></span><span class="action-arrow">→</span></a></section>
 <div class="bottom-grid"><section class="panel"><div class="section-heading"><h3>Ostatnie rozmowy</h3><a class="button subtle" href="#messages">Otwórz rozmowy →</a></div>${state.chats.slice(0,2).map(c=>chatRow(c)).join('')}</section><aside class="tip"><div class="tip-symbol">${uiIcon('documents')}</div><h3>Zanim zaplanujesz krycie</h3><p>Porównaj rodowody, sprawdź aktualne badania i omów warunki z właścicielem. Widoczność profilu nie potwierdza przydatności kota do rozrodu.</p><a href="#documents" class="button subtle">Sprawdź dokumenty →</a></aside></div>`;
}
function cats(){return heading('Moje koty','Profile, które tworzą historię Twojej hodowli.','<button class="button primary" data-add>＋ Dodaj kota</button>')+`<div class="notice">Dodane profile są widoczne tylko w tej demonstracji na Twoim urządzeniu. Zdjęcia przykładowych kotów są wygenerowane, a nowe profile nie mają zdjęcia.</div><div class="cat-grid">${state.cats.filter(c=>c.own).map(catCard).join('')||'<div class="empty"><h3>Dodaj pierwszego kota</h3><p>Uzupełnij podstawowe informacje o swojej hodowli.</p><button class="button primary" data-add>Dodaj kota</button></div>'}</div>`;}
function search(){return heading('Szukaj kota','Poznaj koty i hodowców. Zacznij od rasy, płci i lokalizacji.')+`<div class="notice">To wyszukiwarka profili, nie ocena zgodności genetycznej. Rodowody, zdrowie i warunki krycia wymagają sprawdzenia z hodowcą i odpowiednim specjalistą.</div><form class="filters" id="filters"><label>Imię lub hodowla<input name="query" type="search" placeholder="Szukaj profilu…"></label><label>Rasa<select name="breed"><option value="">Wszystkie rasy</option><option>Maine Coon</option><option>Ragdoll</option><option>Brytyjski krótkowłosy</option><option>Syberyjski</option></select></label><label>Płeć<select name="sex"><option value="">Dowolna</option><option value="MALE">Kocur</option><option value="FEMALE">Kotka</option></select></label><label>Miasto<input name="city" type="search" placeholder="Wszystkie miasta"></label><div class="filter-footer"><label class="check"><input name="available" type="checkbox" checked> Tylko dostępne do kontaktu</label><button type="button" class="button secondary" data-reset-filters>Wyczyść filtry</button></div></form><p class="filter-count" id="filter-count" aria-live="polite"></p><div class="cat-grid" id="search-results"></div>`;}
function filterCats(){const data=new FormData(document.querySelector('#filters'));const contains=(v,q)=>String(v).toLocaleLowerCase('pl').includes(String(q).trim().toLocaleLowerCase('pl'));const matches=state.cats.filter(c=>!c.own&&(!data.get('available')||c.available)&&(!data.get('breed')||c.breed===data.get('breed'))&&(!data.get('sex')||c.sex===data.get('sex'))&&contains(c.name+' '+c.owner,data.get('query'))&&contains(c.city,data.get('city')));document.querySelector('#filter-count').textContent=`Liczba znalezionych profili: ${matches.length}`;document.querySelector('#search-results').innerHTML=matches.map(catCard).join('')||'<div class="empty"><h3>Brak profili dla tych filtrów</h3><p>Zmień rasę, płeć lub miasto, aby zobaczyć inne koty.</p></div>';matchCatsApplyLanguage(state.language);}
function detail(id){const c=state.cats.find(c=>c.id===id);if(!c)return heading('Nie znaleziono profilu','Wybrany profil nie istnieje.')+'<a class="button secondary" href="#search">Wróć do wyszukiwarki</a>';return `<a class="button subtle back" href="#${c.own?'cats':'search'}">← Wróć do ${c.own?'moich kotów':'wyszukiwarki'}</a><div class="detail-layout"><div><div class="cat-picture detail-picture">${catVisual(c)}</div><p class="muted" style="margin:12px 0 22px">${c.id<=5?'Wygenerowane zdjęcie demonstracyjne. Docelowo: zdjęcia dodane przez hodowcę.':'Nie dodano zdjęcia kota.'}</p><div class="panel"><h3>Dokumenty i osiągnięcia</h3>${c.documents.map(d=>`<div class="document-row"><div><strong>${escapeHTML(d)}</strong><small>Przykładowy wpis, bez załączonego pliku</small></div><span class="document-status">Nieweryfikowany</span></div>`).join('')||'<p class="muted" style="margin-top:15px">Nie dodano dokumentów.</p>'}${c.award?'<div class="document-row"><div><strong>Osiągnięcia wystawowe</strong><small>Wpis demonstracyjny — bez potwierdzenia</small></div><span class="document-status">Nieweryfikowany</span></div>':''}</div></div><section class="detail-box"><span class="eyebrow">PROFIL KOTA</span><h1>${escapeHTML(c.name)}</h1><p class="muted">${escapeHTML(c.breed)} · ${sexLabel(c)} · ${age(c)}</p><dl class="detail-facts"><div><dt>Właściciel / hodowla</dt><dd>${escapeHTML(c.own?state.profile.kennel:c.owner)}</dd></div><div><dt>Lokalizacja</dt><dd>${escapeHTML(c.city)}</dd></div><div><dt>Data urodzenia</dt><dd>${escapeHTML(c.birth)}</dd></div><div><dt>Dostępność do kontaktu</dt><dd>${c.available?'Zgłoszona przez właściciela':'Obecnie niedostępny'}</dd></div></dl><h3>O kocie</h3><p class="muted" data-user-text="${c.id>5}" style="margin:12px 0 24px">${escapeHTML(c.description||'Opis nie został uzupełniony.')}</p><div class="notice">Dokumenty nie zostały zweryfikowane. Ten profil nie potwierdza zdrowia, czystości rasy ani przydatności do rozrodu.</div>${c.own?`<button class="button secondary" data-toggle="${c.id}">${c.available?'Wyłącz dostępność do kontaktu':'Włącz dostępność do kontaktu'}</button>`:`<button class="button primary" data-contact="${c.id}">Napisz do hodowcy</button>`}<p class="muted" style="margin-top:15px">Rozmowy w tym podglądzie nie są wysyłane do prawdziwych hodowców.</p></section></div>`;}
function messages(){const chat=state.chats.find(c=>c.id===activeChat)||state.chats[0];activeChat=chat?.id;return heading('Rozmowy','Poznaj hodowcę, zapytaj o dokumenty i omów warunki.')+`<div class="notice">Tryb demonstracyjny: wiadomości zapisują się lokalnie. Nie są wysyłane do innych osób. Nie wpisuj prawdziwych danych osobowych ani poufnych informacji.</div><section class="chat-layout"><div class="chat-list" aria-label="Lista rozmów">${state.chats.map(c=>chatRow(c,c.id===activeChat)).join('')}</div><div class="chat-pane">${chat?`<div class="chat-header"><strong>${escapeHTML(chat.owner)}</strong><small>W sprawie kota: ${escapeHTML(state.cats.find(c=>c.id===chat.catId)?.name||'Profil kota')}</small></div><div class="messages" id="message-list" role="log" aria-label="Historia rozmowy">${chat.messages.map(m=>`<div class="bubble ${m.mine?'mine':''}">${escapeHTML(m.text)}<small>${m.mine?'Ty · ':''}${escapeHTML(m.time)}</small></div>`).join('')||'<p class="muted">Przywitaj się i napisz, o którego kota chcesz zapytać.</p>'}</div><form class="chat-compose" id="message-form"><input name="message" required maxlength="2000" placeholder="Napisz wiadomość demonstracyjną…" aria-label="Treść wiadomości" autocomplete="off"><button type="submit" class="button primary">Dodaj wiadomość</button></form>`:'<div class="empty"><h3>Nie masz jeszcze rozmów</h3><p>Otwórz profil kota i wybierz kontakt z hodowcą.</p><a href="#search" class="button primary">Znajdź kota</a></div>'}</div></section>`;}
function documents(){return heading('Dokumenty kotów','Rodowody, badania i osiągnięcia — uporządkowane w jednym miejscu.')+`<div class="notice">Ten panel pokazuje docelową organizację dokumentów. W tej wersji nie ma przesyłania plików ani weryfikacji ich autentyczności.</div><section class="panel">${state.cats.filter(c=>c.own).map(c=>`<div class="document-row"><div><strong>${escapeHTML(c.name)} · ${escapeHTML(c.breed)}</strong><small>${c.documents.length?escapeHTML(c.documents.join(' · ')):'Brak dokumentów'}</small></div><button class="button secondary" data-cat="${c.id}">Otwórz profil</button></div>`).join('')}</section><div class="bottom-grid"><aside class="tip"><h3>Rodowód i badanie to różne dokumenty</h3><p>Rodowód dokumentuje pochodzenie kota. Wynik badania genetycznego opisuje konkretne przebadane cechy lub warianty. Nie zastępują się nawzajem.</p></aside><aside class="tip"><h3>Docelowo: pliki i daty</h3><p>Każdy dokument będzie miał kategorię, datę, wystawcę i ustawienia widoczności. Dodanie dokumentu nie będzie automatycznie oznaczać jego zatwierdzenia.</p></aside></div>`;}
function settings(){return heading('Twoja hodowla','Podstawowe informacje widoczne w demonstracyjnym panelu.')+`<form id="profile-form" class="panel profile-form"><h3>Profil hodowcy</h3><label>Imię<input name="name" required maxlength="60" value="${escapeHTML(state.profile.name)}"></label><label>Nazwa hodowli<input name="kennel" required maxlength="100" value="${escapeHTML(state.profile.kennel)}"></label><label>Miasto<input name="city" required maxlength="60" value="${escapeHTML(state.profile.city)}"></label><p class="muted">To ustawienia demonstracji, bez konta i logowania. Dane pozostają w tej przeglądarce.</p><div class="settings-actions"><button class="button primary" type="submit">Zapisz ustawienia</button><button class="button secondary danger" type="button" id="reset-demo">Przywróć przykładowe dane</button></div></form>`;}
function render(){const route=location.hash.slice(1)||'dashboard';const [page,id]=route.split('/');const navPage=page==='cat'?(state.cats.find(c=>c.id===Number(id))?.own?'cats':'search'):page;document.querySelector('#navigation').innerHTML=navigation.map(([key,icon,label])=>`<a href="#${key}" class="nav-item ${key===navPage?'active':''}" ${key===navPage?'aria-current="page"':''} title="${label}"><span class="nav-icon" aria-hidden="true">${uiIcon(key)}</span><span class="nav-text">${label}</span>${key==='messages'?`<span class="nav-count">${state.chats.length}</span>`:''}</a>`).join('');document.querySelector('#breadcrumb').textContent=page==='cat'?'Profil kota':navigation.find(n=>n[0]===page)?.[2]||'Start';const views={dashboard,cats,search,messages,documents,settings};main.innerHTML=page==='cat'?detail(Number(id)):(views[page]||dashboard)();document.title=`${document.querySelector('#breadcrumb').textContent} · MatchCats`;if(page==='search'){if(pendingSearch){const form=document.querySelector('#filters');for(const key of ['breed','sex','city'])form.elements[key].value=pendingSearch[key];pendingSearch=null;}filterCats();document.querySelector('#filters').addEventListener('input',filterCats);document.querySelector('#filters').addEventListener('submit',e=>e.preventDefault());}if(page==='messages'){const list=document.querySelector('#message-list');if(list)list.scrollTop=list.scrollHeight;}document.querySelector('.workspace strong').textContent=state.profile.kennel;document.querySelector('.sidebar-bottom strong').textContent=state.profile.name;matchCatsApplyLanguage(state.language);if(!storageAvailable)toast('Zapis lokalny jest niedostępny. Dane mogą zniknąć po zamknięciu strony.');}
function openAdd(){const form=document.querySelector('#cat-form');form.reset();const now=new Date();form.elements.birth.max=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;document.querySelector('#cat-error').textContent='';matchCatsApplyLanguage(state.language);document.querySelector('#cat-dialog').showModal();}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.language){state.language=el.dataset.language;save();render();return;}if(el.hasAttribute('data-add'))openAdd();if(el.dataset.cat)location.hash=`cat/${el.dataset.cat}`;if(el.dataset.chat){activeChat=Number(el.dataset.chat);if(location.hash==='#messages')render();else location.hash='messages';}if(el.hasAttribute('data-reset-filters')){document.querySelector('#filters').reset();filterCats();}if(el.dataset.contact){const cat=state.cats.find(c=>c.id===Number(el.dataset.contact));let chat=state.chats.find(c=>c.catId===cat.id);if(!chat){chat={id:Math.max(0,...state.chats.map(c=>c.id))+1,catId:cat.id,owner:cat.owner,messages:[]};state.chats.push(chat);save();}activeChat=chat.id;location.hash='messages';}if(el.dataset.toggle){const cat=state.cats.find(c=>c.id===Number(el.dataset.toggle));cat.available=!cat.available;save();render();}if(['profile-button','top-profile'].includes(el.id))location.hash='settings';if(['close-dialog','cancel-dialog'].includes(el.id))document.querySelector('#cat-dialog').close();if(el.id==='reset-demo'&&confirm(matchCatsTranslate('Usunąć lokalnie dodane profile, wiadomości i ustawienia oraz przywrócić przykładowe dane?',state.language))){state={language:state.language,cats:structuredClone(initialCats),chats:structuredClone(initialChats),profile:{name:'Wiktoria',kennel:'Twoja hodowla',city:'Warszawa'}};activeChat=1;if(save())toast('Przywrócono dane demonstracyjne.');render();}});
document.addEventListener('submit',e=>{if(e.target.id==='dashboard-search'){e.preventDefault();const data=new FormData(e.target);pendingSearch={breed:data.get('breed'),sex:data.get('sex'),city:data.get('city').trim()};location.hash='search';return;}if(e.target.id==='cat-form'){e.preventDefault();const data=new FormData(e.target);const name=data.get('name').trim(),city=data.get('city').trim(),birth=data.get('birth');if(!name||!city||!birth||new Date(birth)>new Date()){document.querySelector('#cat-error').textContent=matchCatsTranslate('Podaj imię, miasto i poprawną datę urodzenia, która nie jest w przyszłości.',state.language);return;}state.cats.push({id:Math.max(0,...state.cats.map(c=>c.id))+1,name,breed:data.get('breed'),sex:data.get('sex'),birth,city,description:data.get('description').trim(),owner:state.profile.name,own:true,available:!!data.get('available'),tone:state.cats.length%4,documents:[],award:''});const saved=save();document.querySelector('#cat-dialog').close();if(location.hash==='#cats')render();else location.hash='cats';if(saved)toast('Profil kota zapisany na tym urządzeniu.');}if(e.target.id==='message-form'){e.preventDefault();const text=new FormData(e.target).get('message').trim();if(!text)return;const chat=state.chats.find(c=>c.id===activeChat);chat.messages.push({mine:true,text,time:new Date().toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'})});save();render();document.querySelector('#message-form input').focus();}if(e.target.id==='profile-form'){e.preventDefault();const data=new FormData(e.target);const profile={name:data.get('name').trim(),kennel:data.get('kennel').trim(),city:data.get('city').trim()};if(Object.values(profile).some(v=>!v)){toast('Uzupełnij wszystkie pola profilu.');return;}state.profile=profile;const saved=save();render();if(saved)toast('Ustawienia zapisane na tym urządzeniu.');}});
window.addEventListener('hashchange',()=>{render();main.focus({preventScroll:true});window.scrollTo(0,0);});
render();

}
