'use strict';
window.MatchCatsSafety = (() => {
  async function render(route,id,ui) {
    const {api,t,esc,title,button,capabilities,page}=ui;
    const status=value=>({OPEN:t('Oczekuje na ocenę','Awaiting review'),RESOLVED:t('Rozpatrzone','Resolved'),DISMISSED:t('Oddalone','Dismissed')})[value];
    const reason=value=>({SPAM:t('Spam','Spam'),HARASSMENT:t('Nękanie lub obraźliwa treść','Harassment or abusive content'),FRAUD:t('Podejrzenie oszustwa','Suspected fraud'),OTHER:t('Inny problem','Other concern')})[value];
    const pagination=result=>`<div class="live-pages"><button class="button secondary" data-page="${Math.max(0,page-1)}" ${page===0?'disabled':''}>${t('Poprzednie','Previous')}</button><span>${t('Wyników','Results')}: ${result.total}</span><button class="button secondary" data-page="${page+1}" ${(page+1)*20>=result.total?'disabled':''}>${t('Następne','Next')}</button></div>`;
    if(route==='report') {
      const [type,target]=String(id||'').split(':');
      if(!['CAT','MESSAGE'].includes(type)||!/^\d+$/.test(target)||Number(target)<1)throw new MatchCatsAPI.APIError(404,'NOT_FOUND');
      return title(t('Zgłoś problem','Report a concern'))+`<section class="panel live-form"><p>${t('Dotyczy','Target')}: ${type==='CAT'?t('profil kota','cat profile'):t('wiadomość','message')} #${esc(target)}</p><p>${t('Wybrana treść i opis problemu trafią do prywatnej kolejki moderatora. Samo zgłoszenie nie zawiesza konta. Kopia zgłoszonej treści może pozostać po usunięciu konta; zgłoszenia są usuwane po 90 dniach.','The selected content and your description enter a private moderator queue. Reporting does not automatically suspend an account. Reported content may remain after account deletion; reports are deleted after 90 days.')}</p>${!capabilities.moderationConfigured?`<p class="notice">${t('Nie przypisano jeszcze moderatora. Zgłoszenie zostanie zapisane, ale czas odpowiedzi nie jest gwarantowany. Możesz od razu zablokować kontakt.','No moderator has been assigned yet. Your report will be stored, but a response time is not guaranteed. You can block contact immediately.')}</p>`:''}<form id="safety-report-form" data-target-type="${type}" data-target-id="${esc(target)}"><label>${t('Powód','Reason')}<select name="reason">${['SPAM','HARASSMENT','FRAUD','OTHER'].map(r=>`<option value="${r}">${reason(r)}</option>`).join('')}</select></label><label>${t('Opisz problem (10-2000 znaków)','Describe the concern (10-2000 characters)')}<textarea name="details" required minlength="10" maxlength="2000"></textarea></label><button class="button primary" type="submit">${t('Wyślij zgłoszenie','Submit report')}</button></form>${button(t('Moje zgłoszenia i blokady','My reports and blocks'),'safety','secondary')}</section>`;
    }
    if(route==='safety') {
      const [blocks,reports]=await Promise.all([api('/safety/blocks'),api('/safety/reports?page='+page+'&size=20')]);
      return title(t('Bezpieczeństwo i kontakt','Safety and contact'))+`<section class="panel"><h2>${t('Zablokowani hodowcy','Blocked breeders')}</h2><p>${t('Blokada zatrzymuje nowe wiadomości i propozycje par w obu kierunkach. Profile pozostają widoczne, a historia rozmowy zachowuje kontekst zgłoszenia.','Blocking stops new messages and pair proposals in both directions. Profiles remain visible and conversation history keeps the context available for reporting.')}</p>${blocks.map(b=>`<div class="live-file-row"><strong>${esc(b.label)}</strong><button class="button secondary" type="button" data-unblock-owner="${b.accountId}">${t('Odblokuj','Unblock')}</button></div>`).join('')||`<p>${t('Nie blokujesz obecnie żadnego hodowcy.','You have not blocked any breeders.')}</p>`}</section><h2>${t('Moje zgłoszenia','My reports')}</h2>${reports.items.map(r=>`<article class="panel safety-report"><h2>${t('Zgłoszenie','Report')} #${r.id}</h2><p>${status(r.status)} · ${reason(r.reason)}</p><p>${t('Dotyczy','Target')}: ${r.targetType==='CAT'?t('profil kota','cat profile'):t('wiadomość','message')} #${r.targetId}</p><p class="safety-text">${esc(r.details)}</p></article>`).join('')||`<p>${t('Brak zgłoszeń.','No reports.')}</p>`}${pagination(reports)}`;
    }
    if(!capabilities.moderator)throw new MatchCatsAPI.APIError(403,'FORBIDDEN');
    if(id==='documents') {
      const result=await api('/moderation/documents?page='+page+'&size=20');
      return title(t('Sprawdzanie dokumentów','Document reviews'))+button(t('Zgłoszenia i blokady','Reports and blocks'),'moderation','secondary')+`<p>${t('Sprawdź dokument u jego wystawcy. Decyzja dotyczy tego pliku i nie jest gwarancją zdrowia kota ani przydatności do rozmnażania. Uzasadnienie zobaczy właściciel.','Check the document with its issuer. A decision covers this file and does not guarantee the cat’s health or suitability for breeding. The owner will see your explanation.')}</p>`+result.items.map(d=>`<article class="panel safety-report"><h2>${esc(d.filename)}</h2><p>${esc(d.kind)} · ${t('Kot','Cat')} #${d.catId}</p><button class="button secondary" type="button" data-review-download="${d.id}">${t('Pobierz dokument do sprawdzenia','Download for review')}</button><form class="document-review-decision" data-document-id="${d.id}" data-requested-at="${esc(d.verificationRequestedAt)}"><label>${t('Decyzja','Decision')}<select name="status"><option value="REJECTED">${t('Odrzuć','Reject')}</option><option value="VERIFIED">${t('Zatwierdź dokument','Approve document')}</option></select></label><label>${t('Uzasadnienie dla właściciela (do 1000 znaków)','Explanation for the owner (up to 1000 characters)')}<textarea name="note" required maxlength="1000"></textarea></label><button class="button primary" type="submit">${t('Zapisz decyzję','Save decision')}</button></form></article>`).join('')+(!result.items.length?`<p>${t('Brak dokumentów oczekujących na sprawdzenie.','No documents awaiting review.')}</p>`:'')+pagination(result);
    }
    const filter=['OPEN','RESOLVED','DISMISSED'].includes(id)?id:'OPEN';
    const [reports,suspended]=await Promise.all([api('/moderation/reports?status='+filter+'&page='+page+'&size=20'),api('/moderation/suspended')]);
    return title(t('Panel moderatora','Moderator panel'))+button(t('Sprawdzanie dokumentów','Document reviews'),'moderation/documents','secondary')+`<div class="live-tools">${['OPEN','RESOLVED','DISMISSED'].map(s=>button(status(s),'moderation/'+s,filter===s?'primary':'secondary')).join('')}</div>${reports.items.map(r=>`<article class="panel safety-report"><h2>${t('Zgłoszenie','Report')} #${r.id} · ${status(r.status)}</h2><p>${reason(r.reason)} · ${t('Konto objęte zgłoszeniem','Reported account')}: ${r.reportedAccountId??t('usunięte','deleted')}</p><h3>${t('Opis problemu','Concern')}</h3><p class="safety-text">${esc(r.details)}</p><h3>${t('Kopia zgłoszonej treści','Reported content snapshot')}</h3><pre class="safety-evidence">${esc(r.snapshot)}</pre>${r.targetType==='CAT'?button(t('Otwórz profil kota','Open cat profile'),'cat/'+r.targetId,'secondary'):''}${r.status==='OPEN'?`<form class="moderation-decision" data-report-id="${r.id}"><label>${t('Decyzja','Decision')}<select name="decision"><option value="RESOLVED:NONE">${t('Rozpatrz bez zawieszenia','Resolve without suspension')}</option><option value="RESOLVED:SUSPEND_ACCOUNT">${t('Zawieś zgłoszone konto','Suspend reported account')}</option><option value="DISMISSED:NONE">${t('Oddal zgłoszenie','Dismiss report')}</option></select></label><label>${t('Uzasadnienie (prywatne dla moderatorów)','Reason (private to moderators)')}<textarea name="note" required maxlength="2000"></textarea></label><p>${t('Zawieszenie wyloguje konto i ukryje jego koty. Nie usunie danych.','Suspension signs the account out and hides its cats. It does not delete data.')}</p><button class="button primary" type="submit">${t('Zapisz decyzję','Save decision')}</button></form>`:`<p class="safety-text">${esc(r.decisionNote)}</p>`}</article>`).join('')||`<p>${t('Brak zgłoszeń w tej kategorii.','No reports in this category.')}</p>`}${pagination(reports)}<section class="panel live-page"><h2>${t('Zawieszone konta (do 100)','Suspended accounts (up to 100)')}</h2>${suspended.map(a=>`<form class="moderation-reinstate" data-account-id="${a.accountId}"><h3>${esc(a.username)} · #${a.accountId}</h3><label>${t('Powód przywrócenia','Reason for reinstatement')}<input name="note" required maxlength="2000"></label><button class="button secondary" type="submit">${t('Przywróć dostęp','Reinstate access')}</button></form>`).join('')||t('Brak zawieszonych kont.','No suspended accounts.')}</section>`;
  }
  return {render};
})();
