CREATE TABLE mc_moderation_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moderator_id INTEGER REFERENCES mc_accounts(id) ON DELETE SET NULL,
    account_id INTEGER REFERENCES mc_accounts(id) ON DELETE SET NULL,
    action VARCHAR(10) NOT NULL CHECK (action IN ('SUSPEND','REINSTATE')),
    note VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX mc_moderation_actions_created ON mc_moderation_actions(created_at);
