CREATE TABLE mc_document_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES mc_documents(id) ON DELETE CASCADE,
    reviewer_id INTEGER REFERENCES mc_accounts(id) ON DELETE SET NULL,
    requested_at TIMESTAMPTZ NOT NULL,
    reviewed_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(24) NOT NULL CHECK (status IN ('VERIFIED','REJECTED')),
    note VARCHAR(1000) NOT NULL,
    UNIQUE (document_id, requested_at)
);
CREATE INDEX mc_documents_review_queue ON mc_documents(verification_requested_at, id)
    WHERE verification_status = 'REVIEW_REQUESTED';
