CREATE TABLE mc_breeders (
    id INTEGER PRIMARY KEY REFERENCES mc_accounts(id) ON DELETE CASCADE,
    kennel VARCHAR(120) NOT NULL, city VARCHAR(100) NOT NULL, country VARCHAR(100) NOT NULL,
    bio VARCHAR(2000) NOT NULL
);
CREATE TABLE mc_cats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER NOT NULL REFERENCES mc_breeders(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL, breed VARCHAR(100) NOT NULL,
    sex VARCHAR(10) NOT NULL CHECK (sex IN ('MALE','FEMALE')),
    health VARCHAR(10) NOT NULL CHECK (health IN ('UNKNOWN','HEALTHY','SICK')),
    birth_date DATE NOT NULL, city VARCHAR(100) NOT NULL, country VARCHAR(100) NOT NULL,
    description VARCHAR(2000) NOT NULL, available BOOLEAN NOT NULL, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT mc_cats_availability CHECK (NOT available OR health='HEALTHY')
);
CREATE INDEX mc_cats_owner ON mc_cats(owner_id);
CREATE INDEX mc_cats_breed_sex ON mc_cats(lower(breed),sex);
