CREATE TABLE mc_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_owner_id INTEGER NOT NULL REFERENCES mc_accounts(id) ON DELETE CASCADE,
    second_owner_id INTEGER NOT NULL REFERENCES mc_accounts(id) ON DELETE CASCADE,
    context_cat_id INTEGER REFERENCES mc_cats(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (first_owner_id < second_owner_id),
    UNIQUE (first_owner_id, second_owner_id)
);
CREATE INDEX mc_conversations_second_owner ON mc_conversations(second_owner_id);
CREATE TABLE mc_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES mc_conversations(id) ON DELETE CASCADE,
    author_id INTEGER NOT NULL REFERENCES mc_accounts(id) ON DELETE CASCADE,
    text VARCHAR(4000) NOT NULL CHECK (length(trim(text)) > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX mc_messages_conversation_id ON mc_messages(conversation_id, id);
