CREATE TABLE mc_cat_pairs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_cat_id INTEGER NOT NULL REFERENCES mc_cats(id) ON DELETE CASCADE,
    second_cat_id INTEGER NOT NULL REFERENCES mc_cats(id) ON DELETE CASCADE,
    conversation_id BIGINT NOT NULL REFERENCES mc_conversations(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (first_cat_id < second_cat_id),
    UNIQUE (first_cat_id, second_cat_id)
);
CREATE INDEX mc_cat_pairs_second_cat ON mc_cat_pairs(second_cat_id);
