CREATE TABLE mc_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cat_id INTEGER NOT NULL REFERENCES mc_cats(id) ON DELETE CASCADE,
    filename VARCHAR(200) NOT NULL,
    media_type VARCHAR(40) NOT NULL CHECK (media_type IN ('application/pdf','image/png','image/jpeg')),
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('PEDIGREE','GENETIC_TEST','AWARD','HEALTH','OTHER')),
    visibility VARCHAR(20) NOT NULL CHECK (visibility IN ('PRIVATE','BREEDERS')),
    bytes INTEGER NOT NULL CHECK (bytes > 0 AND bytes <= 5242880),
    content BYTEA NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (octet_length(content) = bytes)
);
CREATE INDEX mc_documents_cat ON mc_documents(cat_id);
