ALTER TABLE mc_accounts ADD COLUMN suspended BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE mc_user_blocks (
    blocker_id INTEGER NOT NULL REFERENCES mc_accounts(id) ON DELETE CASCADE,
    blocked_id INTEGER NOT NULL REFERENCES mc_accounts(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (blocker_id, blocked_id),
    CHECK (blocker_id <> blocked_id)
);
CREATE INDEX mc_user_blocks_reverse ON mc_user_blocks(blocked_id, blocker_id);
CREATE TABLE mc_safety_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id INTEGER REFERENCES mc_accounts(id) ON DELETE SET NULL,
    reported_account_id INTEGER REFERENCES mc_accounts(id) ON DELETE SET NULL,
    target_type VARCHAR(10) NOT NULL CHECK (target_type IN ('CAT','MESSAGE')),
    target_id BIGINT NOT NULL,
    reason VARCHAR(20) NOT NULL CHECK (reason IN ('SPAM','HARASSMENT','FRAUD','OTHER')),
    details VARCHAR(2000) NOT NULL CHECK (length(trim(details)) BETWEEN 10 AND 2000),
    snapshot TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(12) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','RESOLVED','DISMISSED')),
    moderator_id INTEGER REFERENCES mc_accounts(id) ON DELETE SET NULL,
    decision_note VARCHAR(2000),
    moderated_at TIMESTAMPTZ
);
CREATE INDEX mc_safety_reports_queue ON mc_safety_reports(status, id);
CREATE INDEX mc_safety_reports_reporter ON mc_safety_reports(reporter_id, created_at);
